{Kazanimlar}|239|555|7|12|E.7.4.R1|Students will be able to understand past and present events in simple texts including explanations and reasons.|Students will be able to understand past and present events in simple texts including explanations and reasons.|A2,B5,
{Kazanimlar}|240|555|7|12|E.7.4.R1|Students will be able to understand past and present events in simple texts including explanations and reasons.|Students will be able to understand past and present events in simple texts including explanations and reasons.|A3,B2,
{Kazanimlar}|241|555|8|12|E.8.2.R1 |Students will be able to understand short and simple invitation letters, cards and e-mails.|Students will be able to understand short and simple invitation letters, cards and e-mails.|A1,B4,
{Kazanimlar}|242|555|8|12|E.8.2.R1 |Students will be able to understand short and simple texts about regular activities of teenagers.|Students will be able to understand short and simple texts about regular activities of teenagers.|A2,B5,
{Kazanimlar}|243|555|8|12|E.8.3.R2|Students will be able to guess the meaning of unknown words from the text.|Students will be able to guess the meaning of unknown words from the text.|A3,B2,
{Kazanimlar}|244|555|8|12|E.8.4.R1 |Students will be able to understand short and simple texts with related vocabulary.|Students will be able to understand short and simple texts with related vocabulary.|A4,B1,
{Kazanimlar}|245|555|8|12|E.8.4.R1|Students will be able to understand short and simple texts with related vocabulary.|Students will be able to understand short and simple texts with related vocabulary.|A5,B3,
{Kazanimlar}|246|555|7|1|T.7.3.25|Metinler arasında karşılaştırma yapar.|Metinler arasında karşılaştırma yapar.|A1,B3,
{Kazanimlar}|247|555|7|1|T.7.3.11|Zarfların metnin anlamına olan katkısını açıklar.|Zarfların metnin anlamına olan katkısını açıklar.|A2,B4,
{Kazanimlar}|248|555|7|1|T.7.3.38|Metindeki iş ve işlem basamaklarını kavrar.|Metindeki iş ve işlem basamaklarını kavrar.|A3,B10,
{Kazanimlar}|249|555|7|1|T.7.4.16|Yazdıklarını düzenler. (Yazım ve noktalama kuralları)|Yazdıklarını düzenler. (Yazım ve noktalama kuralları)|A4,B7,
{Kazanimlar}|250|555|7|1|T.7.3.21|Metindeki hikâye unsurlarını belirler.|Metindeki hikâye unsurlarını belirler.|A5,B8,
{Kazanimlar}|251|555|7|1|T.7.3.28|Okudukları ile ilgili çıkarımlarda bulunur.|Okudukları ile ilgili çıkarımlarda bulunur.|A6,B1,
{Kazanimlar}|252|555|7|1|T.7.3.22|Metnin içeriğini yorumlar. (Sözel mantık)|Metnin içeriğini yorumlar. (Sözel mantık)|A7,B2,
{Kazanimlar}|253|555|7|1|T.7.3.25|Grafik, tablo ve çizelgeyle sunulan bilgileri yorumlar.|Grafik, tablo ve çizelgeyle sunulan bilgileri yorumlar.|A8,B5,
{Kazanimlar}|254|555|7|1|T.7.3.8|Metindeki söz sanatlarını tespit eder.|Metindeki söz sanatlarını tespit eder.|A9,B6,
{Kazanimlar}|255|555|7|1|T.7.3.16|Metnin konusunu belirler.|Metnin konusunu belirler.|A10,B9,
{Kazanimlar}|256|555|8|1|T.8.3.25|Okudukları ile ilgili çıkarımlarda bulunur.|Okudukları ile ilgili çıkarımlarda bulunur.|A1,B5,
{Kazanimlar}|257|555|8|1|T.8.3.17|Metnin ana fikrini/ana duygusunu belirler.|Metnin ana fikrini/ana duygusunu belirler.|A2,B6,A10,B4,
{Kazanimlar}|258|555|8|1|T.8.3.35|Metindeki iş ve işlem basamaklarını kavrar.|Metindeki iş ve işlem basamaklarını kavrar.|A3,B7,
{Kazanimlar}|259|555|8|1|T.8.3.20|Okuduğu metinlerdeki hikâye unsurlarını belirler.|Okuduğu metinlerdeki hikâye unsurlarını belirler.|A4,B8,
{Kazanimlar}|260|555|8|1|T.8.3.18|Cümlenin ögelerini ayırt eder.|Cümlenin ögelerini ayırt eder.|A5,B9,
{Kazanimlar}|261|555|8|1|T.8.2.5|Kelimeleri anlamlarına uygun kullanır.|Kelimeleri anlamlarına uygun kullanır.|A6,B10,
{Kazanimlar}|262|555|8|1|T.8.3.32|Grafik, tablo ve çizelgeyle sunulan bilgileri yorumlar.|Grafik, tablo ve çizelgeyle sunulan bilgileri yorumlar.|A7,B1,
{Kazanimlar}|263|555|8|1|T.8.3.21|Metnin içeriğini yorumlar.|Metnin içeriğini yorumlar.|A8,B2,
{Kazanimlar}|264|555|8|1|T.8.4.16|Yazdıklarını düzenler. (Yazım ve noktalama kuralları)|Yazdıklarını düzenler. (Yazım ve noktalama kuralları)|A9,B3,
{Kazanimlar}|265|555|8|2|M.8.1.3.6|Kareköklü bir ifade ile çarpıldığında, sonucu bir doğal sayı yapan çarpanlara örnek verir.|Kareköklü bir ifade ile çarpıldığında, sonucu bir doğal sayı yapan çarpanlara örnek verir.|A1,B5,
{Kazanimlar}|266|555|8|2|M.8.1.3.1|Tam kare pozitif tam sayılarla bu sayıların karekökleri arasındaki ilişkiyi belirler.|Tam kare pozitif tam sayılarla bu sayıların karekökleri arasındaki ilişkiyi belirler.|A2,B6,
{Kazanimlar}|267|555|8|2|M.8.1.3.7|Ondalık ifadelerin kareköklerini belirler.|Ondalık ifadelerin kareköklerini belirler.|A3,B9,
{Kazanimlar}|268|555|8|2|M.8.2.1.2|Cebirsel ifadelerin çarpımını yapar.|Cebirsel ifadelerin çarpımını yapar.|A4,B10,
{Kazanimlar}|269|555|8|2|M.8.4.1.2|Verileri sütun, daire veya çizgi grafiği ile gösterir ve bu gösterimler arasında uygun olan dönüşümleri yapar.|Verileri sütun, daire veya çizgi grafiği ile gösterir ve bu gösterimler arasında uygun olan dönüşümleri yapar.|A5,B8,
{Kazanimlar}|270|555|8|2|M.8.5.1.1|Bir olaya ait olası durumları belirler.|Bir olaya ait olası durumları belirler.|A6,B1,
{Kazanimlar}|271|555|8|2|M.8.5.1.3|Eşit şansa sahip olan olaylarda her bir çıktının olasılık değerinin eşit olduğunu ve bu değerin 1/n olduğunu çıklar.|Eşit şansa sahip olan olaylarda her bir çıktının olasılık değerinin eşit olduğunu ve bu değerin 1/n olduğunu çıklar.|A7,B2,
{Kazanimlar}|272|555|8|2|M.8.5.1.4|Olasılık değerinin 0 ile 1 arasında (0 ve 1 dâhil) olduğunu anlar.|Olasılık değerinin 0 ile 1 arasında (0 ve 1 dâhil) olduğunu anlar.|A8,B3,
{Kazanimlar}|273|555|8|2|M.8.5.1.5|Basit bir olayın olma olasılığını hesaplar.|Basit bir olayın olma olasılığını hesaplar.|A9,B4,
{Kazanimlar}|274|555|8|2|M.8.5.1.2|“Daha fazla”, “eşit”, “daha az” olasılıklı olayları ayırt eder, örnek verir.|“Daha fazla”, “eşit”, “daha az” olasılıklı olayları ayırt eder, örnek verir.|A10,B7,
{Kazanimlar}|275|555|7|2|M.7.1.2.2|Rasyonel sayıları ondalık gösterimle ifade eder.|Rasyonel sayıları ondalık gösterimle ifade eder.|A1,B10,
{Kazanimlar}|276|555|7|2|M.7.1.3.2|Devirli olan ve olmayan ondalık gösterimleri rasyonel sayı olarak ifade eder.|Devirli olan ve olmayan ondalık gösterimleri rasyonel sayı olarak ifade eder.|A2,B6,
{Kazanimlar}|277|555|7|2|M.7.1.3.3|Rasyonel sayılarla çok adımlı işlemleri yapar.|Rasyonel sayılarla çok adımlı işlemleri yapar.|A3,B7,
{Kazanimlar}|278|555|7|2|M.7.2.2.1|Eşitliğin korunumu ilkesini anlar.|Eşitliğin korunumu ilkesini anlar.|A4,B2,
{Kazanimlar}|279|555|7|2|M.7.2.1.3|Sayı örüntülerinin kuralını harfle ifade eder, kuralı harfle ifade edilen örüntünün istenilen terimini bulur.|Sayı örüntülerinin kuralını harfle ifade eder, kuralı harfle ifade edilen örüntünün istenilen terimini bulur.|A5,B3
{Kazanimlar}|280|555|7|2|M.7.2.1.1|Cebirsel ifadelerle toplama ve çıkarma işlemleri yapar.|Cebirsel ifadelerle toplama ve çıkarma işlemleri yapar.|A6,B8
{Kazanimlar}|281|555|7|2|M.7.1.3.5|Rasyonel sayılarla işlem yapmayı gerektiren problemleri çözer.|Rasyonel sayılarla işlem yapmayı gerektiren problemleri çözer.|A7,B9
{Kazanimlar}|282|555|7|2|M.7.2.1.2|Bir doğal sayı ile bir cebirsel ifadeyi çarpar.|Bir doğal sayı ile bir cebirsel ifadeyi çarpar.|A8,B4
{Kazanimlar}|283|555|7|2|M.7.1.3.4|Rasyonel sayıların kare ve küplerini hesaplar.|Rasyonel sayıların kare ve küplerini hesaplar.|A9,B5
{Kazanimlar}|284|555|7|2|M.7.1.3.2|Rasyonel sayılarla çarpma ve bölme işlemlerini yapar.|Rasyonel sayılarla çarpma ve bölme işlemlerini yapar.|A10,B1,