// <auto-generated />
namespace ODM.CKYazdirDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class konum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(konum));
        
        string IMigrationMetadata.Id
        {
            get { return "202002250811004_konum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
