{Kazanimlar}|530|8|2|M.8.1.1.1|Verilen pozitif tam sayıların pozitif tam sayı çarpanlarını bulur, pozitif tam sayıların pozitif tam sayı çarpanlarını üslü ifadelerin çarpımı şeklinde yazar.||A6,B2,
{Kazanimlar}|530|8|2|M.8.1.3.2|Tam kare olmayan kareköklü bir sayının hangi iki doğal sayı arasında olduğunu belirler.|Tam kare olmayan kareköklü bir sayının hangi iki doğal sayı arasında olduğunu belirler.|A7,B9,
{Kazanimlar}|530|8|2|M.8.1.1.3|Verilen iki doğal sayının aralarında asal olup olmadığını belirler.||A8,B10,
{Kazanimlar}|530|8|2|M.8.1.3.3|Kareköklü bir ifadeyi a KÖK b şeklinde yazar ve a KÖK b şeklindeki ifadede katsayıyı kök içine alır.||A9,B3,
{Kazanimlar}|530|8|2|M.8.1.2.5|Çok büyük ve çok küçük sayıları bilimsel gösterimle ifade eder ve karşılaştırır.||A10,B4,
{Kazanimlar}|530|8|7|E.8.2.R1|Students will be able to understand short and simple texts about regular activities of teenagers.||A1,B2,
{Kazanimlar}|530|8|7|E.8.2.SP1|Students will be able to express what they prefer, like and dislike.||A2,B3,
{Kazanimlar}|530|8|7|E.8.2.SI1|Students will be able to talk about regular activities of teenagers. |Students will be able to talk about regular activities of teenagers. |A3,B5,
{Kazanimlar}|530|8|7|E.8.1.R2|Students will be able to understand short and simple invitation letters, cards and e-mails.||A4,B1,
{Kazanimlar}|530|8|7|E.8.1.W1|Students will be able to write a short and simple letter apologising and giving reasons for not attending a party in response to an invitation. ||A5,B4,
{Kazanimlar}|530|7|7|E.7.1.L1|Students will be able to understand clear, standard speech on appearances and personalities.||A4,B3,
{Kazanimlar}|530|7|7|E.7.2.SP1|Students will be able to talk about routines/daily activities by using frequency adverbs and giving explanations and reasons.||A2,B4,
{Kazanimlar}|530|7|7|E.7.2.R1|Students will be able to understand short and simple texts on sports.|Students will be able to understand short and simple texts on sports.|A3,B2,
{Kazanimlar}|530|7|7|E.7.2.W1|Students will be able to write pieces about routines//daily activities by using frequency adverbs.|Students will be able to write pieces about routines//daily activities by using frequency adverbs.|A5,B1,
{Kazanimlar}|530|7|7|E.7.1.SI1|Students will be able to talk about other people’s appearances and personalities.||A1,B5,
{Kazanimlar}|530|7|3|S.7.1.2|Bireysel ve toplumsal ilişkilerde olumlu iletişim yollarını kullanır||A1,B3,
{Kazanimlar}|530|7|3|S.7.1.3|Medyanın sosyal değişim ve etkileşimdeki rolünü tartışır.|Medyanın sosyal değişim ve etkileşimdeki rolünü tartışır.|A2,B4,
{Kazanimlar}|530|7|3|S.7.1.1|İletişimi etkileyen tutum ve davranışları analiz ederek kendi tutum ve davranışlarını sorgular.|İletişimi etkileyen tutum ve davranışları analiz ederek kendi tutum ve davranışlarını sorgular.|A3,B5,
{Kazanimlar}|530|7|3|S.7.2.2|Osmanlı Devleti'nin fetih siyasetini örnekler üzerinden analiz eder.|Osmanlı Devleti'nin fetih siyasetini örnekler üzerinden analiz eder.|A4,B1,
{Kazanimlar}|530|7|3|S.7.2.1|Tarihsel olay ve yorumlara dayanarak Osmanlı Devleti’nin siyasi güç olarak ortaya çıkış sürecini ve bu süreci etkileyen faktörleri açıklar.|Tarihsel olay ve yorumlara dayanarak Osmanlı Devleti’nin siyasi güç olarak ortaya çıkış sürecini ve bu süreci etkileyen faktörleri açıklar.|A5,B2,
{Kazanimlar}|530|8|5|S.8.2.3|Mondros Ateşkes Anlaşması’nın imzalanması ve uygulanması karşısında Osmanlı yönetiminin, Mustafa Kemal’in ve halkın tutumunu analiz eder.||A1,B5,
{Kazanimlar}|530|8|5|S.8.1.3|Gençlik Döneminde Mustafa Kemalin fikir hayatını etkileyen önemli kişiler ve olayları kavrar||A2,B4,
{Kazanimlar}|530|8|5|S.8.1.2|Mustafa Kemal’in çocukluk ve öğrenim hayatından hareketle onun kişilik özelliklerinin oluşumu hakkında çıkarımlarda bulunur.||A3,B3,
{Kazanimlar}|530|8|5|S.8.1.1|Avrupa’daki gelişmelerin yansımaları bağlamında Osmanlı Devleti’nin yirminci yüzyılın başlarındaki siyasi ve sosyal durumunu kavrar.||A4,B1,
{Kazanimlar}|530|8|5|S.8.2.1|Birinci Dünya Savaşı’nın sebeplerini ve savaşın başlamasına yol açan gelişmeleri kavrar.||A5,B2,
{Kazanimlar}|530|7|4|F.7.1.1.2|Uzay kirliliğinin nedenlerini ifade ederek bu kirliliğin yol açabileceği olası sonuçları tahmin eder.|Uzay kirliliğinin nedenlerini ifade ederek bu kirliliğin yol açabileceği olası sonuçları tahmin eder.|A1,B6,
{Kazanimlar}|530|7|4|F.7.1.1.4|Teleskobun yapısını ve ne işe yaradığını açıklar.|Teleskobun yapısını ve ne işe yaradığını açıklar.|A4,B3,
{Kazanimlar}|530|7|4|F.7.1.1.6|Basit bir teleskop modeli hazırlayarak sunar.|Basit bir teleskop modeli hazırlayarak sunar.|A6,B2,
{Kazanimlar}|530|7|4|F.7.1.2.1-2-3|Yıldız oluşum sürecinin farkına varır. Yıldız kavramını açıklar. Galaksilerin yapısını açıklar.|Yıldız oluşum sürecinin farkına varır. Yıldız kavramını açıklar. Galaksilerin yapısını açıklar.|A2,B7,
{Kazanimlar}|530|7|4|F.7.1.2.4|Evren kavramını açıklar|Evren kavramını açıklar|A10,B9,
{Kazanimlar}|530|7|4|F.7.2.1.1|Hayvan ve bitki hücrelerinin temel kısımlarını karşılaştırır.|Hayvan ve bitki hücrelerinin temel kısımlarını karşılaştırır.|A7,B1,
{Kazanimlar}|530|7|4|F.7.2.1.3|Hücre-doku-organ-sistem-organizma ilişkisini açıklar.|Hücre-doku-organ-sistem-organizma ilişkisini açıklar.|A3,B5,
{Kazanimlar}|530|7|4|F.7.2.2.1|Mitozun canlılar için önemini açıklar.|Mitozun canlılar için önemini açıklar.|A8,B10,
{Kazanimlar}|530|7|4|F.7.2.2.2|Mitozun birbirini takip eden farklı evrelerden oluştuğunu açıklar. |Mitozun birbirini takip eden farklı evrelerden oluştuğunu açıklar. |A5,B4,
{Kazanimlar}|530|7|4|F.7.2.3.1|Mayozun canlılar için önemini açıklar.|Mayozun canlılar için önemini açıklar.|A9,B8,
{Kazanimlar}|530|8|4|F.8.1.1.1|Mevsimlerin oluşumuna yönelik tahminlerde bulunur.|Mevsimlerin oluşumuna yönelik tahminlerde bulunur.|A10,B4,
{Kazanimlar}|530|8|4|F.8.1.2.2|İklim biliminin (klimatoloji) bir bilim dalı olduğunu ve bu alanda çalışan uzmanlara iklim bilimci (klimatolog) adı verildiğini söyler.|İklim biliminin (klimatoloji) bir bilim dalı olduğunu ve bu alanda çalışan uzmanlara iklim bilimci (klimatolog) adı verildiğini söyler.|A3,B1,
{Kazanimlar}|530|8|4|F.8.1.2.1|İklim ve Hava Olayları Arasındaki Farkı Açıklar.|İklim ve Hava Olayları Arasındaki Farkı Açıklar.|A6,B2,
{Kazanimlar}|530|8|4|F.8.1.2.1|İklim ve hava olayları arasındaki farkı açıklar.|İklim ve hava olayları arasındaki farkı açıklar.|A4,B9,
{Kazanimlar}|530|8|4|F.8.2.1.1|Nükleotid, gen, DNA ve kromozom kavramlarını açıklayarak bu kavramlar arasında ilişki kurar.|Nükleotid, gen, DNA ve kromozom kavramlarını açıklayarak bu kavramlar arasında ilişki kurar.|A1,B7,
{Kazanimlar}|530|8|4|F.8.1.2.1|DNA’nın yapısını model üzerinde gösterir.|DNA’nın yapısını model üzerinde gösterir.|A7,B3,
{Kazanimlar}|530|8|4|F.8.2.1.3|DNA’nın kendini nasıl eşlediğini ifade eder.|DNA’nın kendini nasıl eşlediğini ifade eder.|A5,B10,
{Kazanimlar}|530|8|4|F.8.2.2.1|Kalıtım ile ilgili kavramları tanımlar.|Kalıtım ile ilgili kavramları tanımlar.|A2,B8,
{Kazanimlar}|530|8|4|F.8.2.2.1|Kalıtım ile ilgili kavramları tanımlar.|Kalıtım ile ilgili kavramları tanımlar.|A8,B5,
{Kazanimlar}|530|8|4|F.8.2.2.2|Tek karakter çaprazlamaları ile ilgili problemler çözerek sonuçlar hakkında yorum yapar.|Tek karakter çaprazlamaları ile ilgili problemler çözerek sonuçlar hakkında yorum yapar.|A9,B6,
