{Kazanimlar}|26|530|7|1|T.7.3.20|Metinle ilgili sorular sorar.|Metinle ilgili sorular sorar.|A1,B5
{Kazanimlar}|27|530|7|1|T.7.3.9|Çekim eklerinin işlevlerini ayırt eder.|Çekim eklerinin işlevlerini ayırt eder.|A2,B6
{Kazanimlar}|28|530|7|1|T.7.3.5|Bağlamdan hareketle bilmediği kelime ve kelime gruplarının anlamını tahmin eder.|Bağlamdan hareketle bilmediği kelime ve kelime gruplarının anlamını tahmin eder.|A3,B7,
{Kazanimlar}|29|530|7|1|T.7.3.8|Metindeki söz sanatlarını tespit eder.|Metindeki söz sanatlarını tespit eder.|A4,B8,
{Kazanimlar}|30|530|7|1|T.7.3.23|Metnin içeriğine uygun başlık/başlıklar belirler.|Metnin içeriğine uygun başlık/başlıklar belirler.|A5,B9,
{Kazanimlar}|31|530|7|1|T.7.3.6|Deyim ve atasözlerinin metne katkısını belirler.||A7,B1,
{Kazanimlar}|32|530|7|1|T.7.3.12|Fiillerin anlam özelliklerini fark eder.|Fiillerin anlam özelliklerini fark eder.|A10,B4,
{Kazanimlar}|33|530|7|1|T.7.3.17|Metnin ana fikrini/ana duygusunu belirler.|Metnin ana fikrini/ana duygusunu belirler.|A6,A8,B10,B2,
{Kazanimlar}|34|530|7|1|T.7.3.21|Metindeki hikâye unsurlarını belirler.|Metindeki hikâye unsurlarını belirler.|A9,B3,
{Kazanimlar}|35|530|8|1|T.8.3.5|Bağlamdan yararlanarak bilmediği kelime ve kelime gruplarının anlamını tahmin eder.|Bağlamdan yararlanarak bilmediği kelime ve kelime gruplarının anlamını tahmin eder.|A1,B8,
{Kazanimlar}|36|530|8|1|T.8.3.15|Metinle ilgili sorular sorar.|Metinle ilgili sorular sorar.|A10,B2,
{Kazanimlar}|37|530|8|1|T.8.3.25|Okudukları ile ilgili çıkarımlarda bulunur.|Okudukları ile ilgili çıkarımlarda bulunur.|A2,A3,B9,B10
{Kazanimlar}|39|530|8|1|T.8.3.9|Fiilimsilerin cümledeki işlevlerini kavrar.|Fiilimsilerin cümledeki işlevlerini kavrar.|A4,A8,B3,B7,
{Kazanimlar}|40|530|8|1|T.8.3.11|Metindeki anlatım biçimlerini belirler.|Metindeki anlatım biçimlerini belirler.|A5,B4,
{Kazanimlar}|41|530|8|1|T.8.3.17|Metnin ana fikrini/ana duygusunu belirler.|Metnin ana fikrini/ana duygusunu belirler.|A6,B5,
{Kazanimlar}|42|530|8|1|T.8.3.23|Metinler arasında karşılaştırma yapar.|Metinler arasında karşılaştırma yapar.|A7,B6,
{Kazanimlar}|43|530|8|1|T.8.3.19|Metnin içeriğine uygun başlık/başlıklar belirler.|Metnin içeriğine uygun başlık/başlıklar belirler.|A9,B1,
{Kazanimlar}|44|530|8|6|D.8.1.1|Kader ve kaza inancını ayet ve hadislerle açıklar.|Kader ve kaza inancını ayet ve hadislerle açıklar.|A2,B1,
{Kazanimlar}|45|530|8|6|D.8.1.2|İnsanın ilmi, iradesi, sorumluluğu ile kader arasında ilişki kurar. |İnsanın ilmi, iradesi, sorumluluğu ile kader arasında ilişki kurar. |A3,B2,
{Kazanimlar}|46|530|8|6|D.8.1.3|Kaza ve kader ile ilgili kavramları analiz eder.|Kaza ve kader ile ilgili kavramları analiz eder.|A4,B3,
{Kazanimlar}|47|530|8|6|D.8.1.4|Toplumda kader ve kaza ile ilgili yaygın olan yanlış anlayışları sorgular. |Toplumda kader ve kaza ile ilgili yaygın olan yanlış anlayışları sorgular. |A5,B4,
{Kazanimlar}|48|530|8|6|D.8.1.5.|Hz. Musa’nın (a.s.) hayatını ana hatlarıyla tanır.|Hz. Musa’nın (a.s.) hayatını ana hatlarıyla tanır.|A1,B5,
{Kazanimlar}|49|530|7|6|D.7.1.1|Varlıklar âlemini özelliklerine göre ayırt eder. |Varlıklar âlemini özelliklerine göre ayırt eder. |A5,B3,
{Kazanimlar}|50|530|7|6|D.7.1.2|Melekleri özellikleri ve görevlerine göre sınıflandırır. |Melekleri özellikleri ve görevlerine göre sınıflandırır. |A3,B1,
{Kazanimlar}|51|530|7|6|D.7.1.3|Dünya hayatı ile ahiret hayatı arasındaki ilişkiyi yorumlar. |Dünya hayatı ile ahiret hayatı arasındaki ilişkiyi yorumlar. |A2,B4,
{Kazanimlar}|52|530|7|6|D.7.1.4|Ahiret hayatının aşamalarını açıklar. |Ahiret hayatının aşamalarını açıklar. |A4,B2,
{Kazanimlar}|53|530|7|6|D.7.1.6|Hz. İsa’nın (a.s.) hayatını ana hatlarıyla tanır.||A1,B5,
{Kazanimlar}|54|530|7|2|M.7.1.1.3|Tam sayılarla çarpma ve bölme işlemlerini yapar.|Tam sayılarla çarpma ve bölme işlemlerini yapar.|A1,B8,
{Kazanimlar}|55|530|7|2|M.7.1.1.2|Toplama işleminin özelliklerini akıcı işlem yapmak için birer strateji olarak kullanır.|Toplama işleminin özelliklerini akıcı işlem yapmak için birer strateji olarak kullanır.|A2,B9,
{Kazanimlar}|56|530|7|2|M.7.1.1.5|Tam sayılarla işlemler yapmayı gerektiren problemleri çözer.|Tam sayılarla işlemler yapmayı gerektiren problemleri çözer.|A3,B10,
{Kazanimlar}|57|530|7|2|M.7.1.1.1|Tam sayılarla toplama ve çıkarma işlemlerini yapar, ilgili problemleri çözer.|Tam sayılarla toplama ve çıkarma işlemlerini yapar, ilgili problemleri çözer.|A4,B4,
{Kazanimlar}|58|530|7|2|M.7.1.2.1|Rasyonel sayıları tanır ve sayı doğrusunda gösterir.|Rasyonel sayıları tanır ve sayı doğrusunda gösterir.|A5,B5,
{Kazanimlar}|59|530|7|2|M.7.1.1.3|Tam sayılarla çarpma ve bölme işlemlerini yapar.|Tam sayılarla çarpma ve bölme işlemlerini yapar.|A6,B6,
{Kazanimlar}|60|530|7|2|M.7.1.2.1|Rasyonel sayıları tanır ve sayı doğrusunda gösterir.|Rasyonel sayıları tanır ve sayı doğrusunda gösterir.|A7,B7,
{Kazanimlar}|61|530|7|2|M.7.1.1.4|Tam sayıların kendileri ile tekrarlı çarpımını üslü nicelik olarak ifade eder.|Tam sayıların kendileri ile tekrarlı çarpımını üslü nicelik olarak ifade eder.|A8,B2,
{Kazanimlar}|62|530|7|2|M.7.1.1.5|Tam sayılarla işlemler yapmayı gerektiren problemleri çözer.|Tam sayılarla işlemler yapmayı gerektiren problemleri çözer.|A9,B3,
{Kazanimlar}|63|530|7|2|M.7.1.1.1|Tam sayılarla toplama ve çıkarma işlemlerini yapar, ilgili problemleri çözer.|Tam sayılarla toplama ve çıkarma işlemlerini yapar, ilgili problemleri çözer.|A10,B1,
{Kazanimlar}|64|530|8|2|M.8.1.1.2| İki doğal sayının en büyük ortak bölenini (EBOB) ve en küçük ortak katını (EKOK) hesaplar, ilgili problemleri çözer.||A1,B5,
{Kazanimlar}|65|530|8|2|M.8.1.2.4|Verilen bir sayıyı 10’un farklı tam sayı kuvvetlerini kullanarak ifade eder.||A2,B6,
{Kazanimlar}|66|530|8|2|M.8.1.3.1|Tam kare pozitif tam sayılarla bu sayıların karekökleri arasındaki ilişkiyi belirler.||A3,B7,
{Kazanimlar}|67|530|8|2|M.8.1.2.2|Üslü ifadelerle ilgili temel kuralları anlar, birbirine denk ifadeler oluşturur.||A4,B8,
{Kazanimlar}|68|530|8|2|M.8.1.2.3|Sayıların ondalık gösterimlerini 10’un tam sayı kuvvetlerini kullanarak çözümler.||A5,B1,
{Kazanimlar}|69|530|8|2|M.8.1.1.1|Verilen pozitif tam sayıların pozitif tam sayı çarpanlarını bulur, pozitif tam sayıların pozitif tam sayı çarpanlarını üslü ifadelerin çarpımı şeklinde yazar.||A6,B2,
{Kazanimlar}|70|530|8|2|M.8.1.3.2|Tam kare olmayan kareköklü bir sayının hangi iki doğal sayı arasında olduğunu belirler.|Tam kare olmayan kareköklü bir sayının hangi iki doğal sayı arasında olduğunu belirler.|A7,B9,
{Kazanimlar}|71|530|8|2|M.8.1.1.3|Verilen iki doğal sayının aralarında asal olup olmadığını belirler.||A8,B10,
{Kazanimlar}|72|530|8|2|M.8.1.3.3|Kareköklü bir ifadeyi a KÖK b şeklinde yazar ve a KÖK b şeklindeki ifadede katsayıyı kök içine alır.||A9,B3,
{Kazanimlar}|73|530|8|2|M.8.1.2.5|Çok büyük ve çok küçük sayıları bilimsel gösterimle ifade eder ve karşılaştırır.||A10,B4,
{Kazanimlar}|74|530|8|7|E.8.2.R1|Students will be able to understand short and simple texts about regular activities of teenagers.||A1,B2,
{Kazanimlar}|75|530|8|7|E.8.2.SP1|Students will be able to express what they prefer, like and dislike.||A2,B3,
{Kazanimlar}|76|530|8|7|E.8.2.SI1|Students will be able to talk about regular activities of teenagers. |Students will be able to talk about regular activities of teenagers. |A3,B5,
{Kazanimlar}|77|530|8|7|E.8.1.R2|Students will be able to understand short and simple invitation letters, cards and e-mails.||A4,B1,
{Kazanimlar}|78|530|8|7|E.8.1.W1|Students will be able to write a short and simple letter apologising and giving reasons for not attending a party in response to an invitation. ||A5,B4,
{Kazanimlar}|79|530|7|7|E.7.1.L1|Students will be able to understand clear, standard speech on appearances and personalities.||A4,B3,
{Kazanimlar}|80|530|7|7|E.7.2.SP1|Students will be able to talk about routines/daily activities by using frequency adverbs and giving explanations and reasons.||A2,B4,
{Kazanimlar}|81|530|7|7|E.7.2.R1|Students will be able to understand short and simple texts on sports.|Students will be able to understand short and simple texts on sports.|A3,B2,
{Kazanimlar}|82|530|7|7|E.7.2.W1|Students will be able to write pieces about routines//daily activities by using frequency adverbs.|Students will be able to write pieces about routines//daily activities by using frequency adverbs.|A5,B1,
{Kazanimlar}|83|530|7|7|E.7.1.SI1|Students will be able to talk about other people’s appearances and personalities.||A1,B5,
{Kazanimlar}|84|530|7|3|S.7.1.2|Bireysel ve toplumsal ilişkilerde olumlu iletişim yollarını kullanır||A1,B3,
{Kazanimlar}|85|530|7|3|S.7.1.3|Medyanın sosyal değişim ve etkileşimdeki rolünü tartışır.|Medyanın sosyal değişim ve etkileşimdeki rolünü tartışır.|A2,B4,
{Kazanimlar}|86|530|7|3|S.7.1.1|İletişimi etkileyen tutum ve davranışları analiz ederek kendi tutum ve davranışlarını sorgular.|İletişimi etkileyen tutum ve davranışları analiz ederek kendi tutum ve davranışlarını sorgular.|A3,B5,
{Kazanimlar}|87|530|7|3|S.7.2.2|Osmanlı Devleti'nin fetih siyasetini örnekler üzerinden analiz eder.|Osmanlı Devleti'nin fetih siyasetini örnekler üzerinden analiz eder.|A4,B1,
{Kazanimlar}|88|530|7|3|S.7.2.1|Tarihsel olay ve yorumlara dayanarak Osmanlı Devleti’nin siyasi güç olarak ortaya çıkış sürecini ve bu süreci etkileyen faktörleri açıklar.|Tarihsel olay ve yorumlara dayanarak Osmanlı Devleti’nin siyasi güç olarak ortaya çıkış sürecini ve bu süreci etkileyen faktörleri açıklar.|A5,B2,
{Kazanimlar}|89|530|8|5|S.8.2.3|Mondros Ateşkes Anlaşması’nın imzalanması ve uygulanması karşısında Osmanlı yönetiminin, Mustafa Kemal’in ve halkın tutumunu analiz eder.||A1,B5,
{Kazanimlar}|90|530|8|5|S.8.1.3|Gençlik Döneminde Mustafa Kemalin fikir hayatını etkileyen önemli kişiler ve olayları kavrar||A2,B4,
{Kazanimlar}|91|530|8|5|S.8.1.2|Mustafa Kemal’in çocukluk ve öğrenim hayatından hareketle onun kişilik özelliklerinin oluşumu hakkında çıkarımlarda bulunur.||A3,B3,
{Kazanimlar}|92|530|8|5|S.8.1.1|Avrupa’daki gelişmelerin yansımaları bağlamında Osmanlı Devleti’nin yirminci yüzyılın başlarındaki siyasi ve sosyal durumunu kavrar.||A4,B1,
{Kazanimlar}|93|530|8|5|S.8.2.1|Birinci Dünya Savaşı’nın sebeplerini ve savaşın başlamasına yol açan gelişmeleri kavrar.||A5,B2,
{Kazanimlar}|94|530|7|4|F.7.1.1.2|Uzay kirliliğinin nedenlerini ifade ederek bu kirliliğin yol açabileceği olası sonuçları tahmin eder.|Uzay kirliliğinin nedenlerini ifade ederek bu kirliliğin yol açabileceği olası sonuçları tahmin eder.|A1,B6,
{Kazanimlar}|95|530|7|4|F.7.1.1.4|Teleskobun yapısını ve ne işe yaradığını açıklar.|Teleskobun yapısını ve ne işe yaradığını açıklar.|A4,B3,
{Kazanimlar}|96|530|7|4|F.7.1.1.6|Basit bir teleskop modeli hazırlayarak sunar.|Basit bir teleskop modeli hazırlayarak sunar.|A6,B2,
{Kazanimlar}|97|530|7|4|F.7.1.2.1-2-3|Yıldız oluşum sürecinin farkına varır. Yıldız kavramını açıklar. Galaksilerin yapısını açıklar.|Yıldız oluşum sürecinin farkına varır. Yıldız kavramını açıklar. Galaksilerin yapısını açıklar.|A2,B7,
{Kazanimlar}|98|530|7|4|F.7.1.2.4|Evren kavramını açıklar|Evren kavramını açıklar|A10,B9,
{Kazanimlar}|99|530|7|4|F.7.2.1.1|Hayvan ve bitki hücrelerinin temel kısımlarını karşılaştırır.|Hayvan ve bitki hücrelerinin temel kısımlarını karşılaştırır.|A7,B1,
{Kazanimlar}|100|530|7|4|F.7.2.1.3|Hücre-doku-organ-sistem-organizma ilişkisini açıklar.|Hücre-doku-organ-sistem-organizma ilişkisini açıklar.|A3,B5,
{Kazanimlar}|101|530|7|4|F.7.2.2.1|Mitozun canlılar için önemini açıklar.|Mitozun canlılar için önemini açıklar.|A8,B10,
{Kazanimlar}|102|530|7|4|F.7.2.2.2|Mitozun birbirini takip eden farklı evrelerden oluştuğunu açıklar. |Mitozun birbirini takip eden farklı evrelerden oluştuğunu açıklar. |A5,B4,
{Kazanimlar}|103|530|7|4|F.7.2.3.1|Mayozun canlılar için önemini açıklar.|Mayozun canlılar için önemini açıklar.|A9,B8,
{Kazanimlar}|104|530|8|4|F.8.1.1.1|Mevsimlerin oluşumuna yönelik tahminlerde bulunur.|Mevsimlerin oluşumuna yönelik tahminlerde bulunur.|A10,B4,
{Kazanimlar}|105|530|8|4|F.8.1.2.2|İklim biliminin (klimatoloji) bir bilim dalı olduğunu ve bu alanda çalışan uzmanlara iklim bilimci (klimatolog) adı verildiğini söyler.|İklim biliminin (klimatoloji) bir bilim dalı olduğunu ve bu alanda çalışan uzmanlara iklim bilimci (klimatolog) adı verildiğini söyler.|A3,B1,
{Kazanimlar}|106|530|8|4|F.8.1.2.1|İklim ve Hava Olayları Arasındaki Farkı Açıklar.|İklim ve Hava Olayları Arasındaki Farkı Açıklar.|A6,B2,
{Kazanimlar}|107|530|8|4|F.8.1.2.1|İklim ve hava olayları arasındaki farkı açıklar.|İklim ve hava olayları arasındaki farkı açıklar.|A4,B9,
{Kazanimlar}|108|530|8|4|F.8.2.1.1|Nükleotid, gen, DNA ve kromozom kavramlarını açıklayarak bu kavramlar arasında ilişki kurar.|Nükleotid, gen, DNA ve kromozom kavramlarını açıklayarak bu kavramlar arasında ilişki kurar.|A1,B7,
{Kazanimlar}|109|530|8|4|F.8.1.2.1|DNA’nın yapısını model üzerinde gösterir.|DNA’nın yapısını model üzerinde gösterir.|A7,B3,
{Kazanimlar}|110|530|8|4|F.8.2.1.3|DNA’nın kendini nasıl eşlediğini ifade eder.|DNA’nın kendini nasıl eşlediğini ifade eder.|A5,B10,
{Kazanimlar}|111|530|8|4|F.8.2.2.1|Kalıtım ile ilgili kavramları tanımlar.|Kalıtım ile ilgili kavramları tanımlar.|A2,B8,
{Kazanimlar}|112|530|8|4|F.8.2.2.1|Kalıtım ile ilgili kavramları tanımlar.|Kalıtım ile ilgili kavramları tanımlar.|A8,B5,
{Kazanimlar}|113|530|8|4|F.8.2.2.2|Tek karakter çaprazlamaları ile ilgili problemler çözerek sonuçlar hakkında yorum yapar.|Tek karakter çaprazlamaları ile ilgili problemler çözerek sonuçlar hakkında yorum yapar.|A9,B6,
