//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM.AktifSinavServisRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AktifSinavServisRef.AktifSinavSoap")]
    public interface AktifSinavSoap {
        
        // CODEGEN: Generating message contract since element name access from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuncelSinav", ReplyAction="*")]
        ODM.AktifSinavServisRef.GuncelSinavResponse GuncelSinav(ODM.AktifSinavServisRef.GuncelSinavRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuncelSinav", ReplyAction="*")]
        System.Threading.Tasks.Task<ODM.AktifSinavServisRef.GuncelSinavResponse> GuncelSinavAsync(ODM.AktifSinavServisRef.GuncelSinavRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ODM.AktifSinavServisRef.HelloWorldResponse HelloWorld(ODM.AktifSinavServisRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ODM.AktifSinavServisRef.HelloWorldResponse> HelloWorldAsync(ODM.AktifSinavServisRef.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuncelSinavRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuncelSinav", Namespace="http://tempuri.org/", Order=0)]
        public ODM.AktifSinavServisRef.GuncelSinavRequestBody Body;
        
        public GuncelSinavRequest() {
        }
        
        public GuncelSinavRequest(ODM.AktifSinavServisRef.GuncelSinavRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuncelSinavRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sinavId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int veriGirisi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string access;
        
        public GuncelSinavRequestBody() {
        }
        
        public GuncelSinavRequestBody(int sinavId, int veriGirisi, string access) {
            this.sinavId = sinavId;
            this.veriGirisi = veriGirisi;
            this.access = access;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuncelSinavResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuncelSinavResponse", Namespace="http://tempuri.org/", Order=0)]
        public ODM.AktifSinavServisRef.GuncelSinavResponseBody Body;
        
        public GuncelSinavResponse() {
        }
        
        public GuncelSinavResponse(ODM.AktifSinavServisRef.GuncelSinavResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GuncelSinavResponseBody {
        
        public GuncelSinavResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ODM.AktifSinavServisRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ODM.AktifSinavServisRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ODM.AktifSinavServisRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ODM.AktifSinavServisRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AktifSinavSoapChannel : ODM.AktifSinavServisRef.AktifSinavSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AktifSinavSoapClient : System.ServiceModel.ClientBase<ODM.AktifSinavServisRef.AktifSinavSoap>, ODM.AktifSinavServisRef.AktifSinavSoap {
        
        public AktifSinavSoapClient() {
        }
        
        public AktifSinavSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AktifSinavSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AktifSinavSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AktifSinavSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ODM.AktifSinavServisRef.GuncelSinavResponse ODM.AktifSinavServisRef.AktifSinavSoap.GuncelSinav(ODM.AktifSinavServisRef.GuncelSinavRequest request) {
            return base.Channel.GuncelSinav(request);
        }
        
        public void GuncelSinav(int sinavId, int veriGirisi, string access) {
            ODM.AktifSinavServisRef.GuncelSinavRequest inValue = new ODM.AktifSinavServisRef.GuncelSinavRequest();
            inValue.Body = new ODM.AktifSinavServisRef.GuncelSinavRequestBody();
            inValue.Body.sinavId = sinavId;
            inValue.Body.veriGirisi = veriGirisi;
            inValue.Body.access = access;
            ODM.AktifSinavServisRef.GuncelSinavResponse retVal = ((ODM.AktifSinavServisRef.AktifSinavSoap)(this)).GuncelSinav(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ODM.AktifSinavServisRef.GuncelSinavResponse> ODM.AktifSinavServisRef.AktifSinavSoap.GuncelSinavAsync(ODM.AktifSinavServisRef.GuncelSinavRequest request) {
            return base.Channel.GuncelSinavAsync(request);
        }
        
        public System.Threading.Tasks.Task<ODM.AktifSinavServisRef.GuncelSinavResponse> GuncelSinavAsync(int sinavId, int veriGirisi, string access) {
            ODM.AktifSinavServisRef.GuncelSinavRequest inValue = new ODM.AktifSinavServisRef.GuncelSinavRequest();
            inValue.Body = new ODM.AktifSinavServisRef.GuncelSinavRequestBody();
            inValue.Body.sinavId = sinavId;
            inValue.Body.veriGirisi = veriGirisi;
            inValue.Body.access = access;
            return ((ODM.AktifSinavServisRef.AktifSinavSoap)(this)).GuncelSinavAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ODM.AktifSinavServisRef.HelloWorldResponse ODM.AktifSinavServisRef.AktifSinavSoap.HelloWorld(ODM.AktifSinavServisRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ODM.AktifSinavServisRef.HelloWorldRequest inValue = new ODM.AktifSinavServisRef.HelloWorldRequest();
            inValue.Body = new ODM.AktifSinavServisRef.HelloWorldRequestBody();
            ODM.AktifSinavServisRef.HelloWorldResponse retVal = ((ODM.AktifSinavServisRef.AktifSinavSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ODM.AktifSinavServisRef.HelloWorldResponse> ODM.AktifSinavServisRef.AktifSinavSoap.HelloWorldAsync(ODM.AktifSinavServisRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ODM.AktifSinavServisRef.HelloWorldResponse> HelloWorldAsync() {
            ODM.AktifSinavServisRef.HelloWorldRequest inValue = new ODM.AktifSinavServisRef.HelloWorldRequest();
            inValue.Body = new ODM.AktifSinavServisRef.HelloWorldRequestBody();
            return ((ODM.AktifSinavServisRef.AktifSinavSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
